from .homepage_locators import HomePageLocators
from .detailpage_locators import DetailPageLocators
from .searchpage_locators import SearchPageLocators
from .loginpage_locators import LoginPageLocators
